# Generated by Django 3.1.14 on 2022-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(help_text='A language code that pygments can use to load the appropriate syntax-highlighting module', max_length=50),
        ),
        migrations.AlterField(
            model_name='language',
            name='mime_type',
            field=models.CharField(help_text='A MIME type to use when sending a snippet file in this language', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='The name of the language', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(help_text='A unique slug to identify it in URLs', unique=True),
        ),
    ]
