# Generated by Django 3.1.14 on 2022-05-26 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cab', '0002_auto_20220526_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='author',
            field=models.ForeignKey(help_text='A foreign key to Django’s User model to represent the snippet’s author.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(help_text='The actual code'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='highlighted_code',
            field=models.TextField(editable=False, help_text='Syntax-highlighted HTML version separate from the original code'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.ForeignKey(help_text='A foreign key pointing at the Language the snippet is written in', on_delete=django.db.models.deletion.CASCADE, to='cab.language'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='pub_date',
            field=models.DateTimeField(editable=False, help_text='The date and time when the snippet was first posted'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=tagging.fields.TagField(blank=True, help_text='A list of tags', max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='updated_date',
            field=models.DateTimeField(editable=False, help_text='The date and time when it was last updated'),
        ),
    ]
